(() => {
  'use strict';
  const URL='https://tdzqkygwrdqqpjwculmf.supabase.co';
  const KEY='sb_publishable__ITeCtWl3mFC7sqU0JlJvA_GkFUHRXl';
  const PENDING='admissionflow_pending_signup_v4';
  const STATUSES=['New','Contacted','Interested','Demo booked','Joined','Not interested'];
  let db=null,state=null;
  const app=document.getElementById('app');
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const slugify=v=>String(v||'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').replace(/-+/g,'-');
  const route=location.pathname.replace(/^\/+|\/+$/g,'').split('/').filter(Boolean); const routeName=route[0]||'';
  const page=h=>app.innerHTML='<div class="wrap">'+h+'</div>';
  const msg=(t,k='ok')=>{const e=document.getElementById('msg');if(e){e.textContent=t;e.className=k}};
  const fail=e=>{page('<div class="card"><h2>AdmissionFlow</h2><p class="err">'+esc(e?.message||e||'Unexpected error')+'</p><button id="reload">Reload</button></div>');document.getElementById('reload').onclick=()=>location.reload()};
  const dbInit=()=>{if(!db){if(!window.supabase?.createClient)throw new Error('Supabase client failed to load.');db=window.supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}})}return db};
  const session=async()=>{const {data,error}=await dbInit().auth.getSession();if(error)throw error;return data.session};
  async function finishPending(){
    const raw=localStorage.getItem(PENDING);if(!raw)return false;
    let p;try{p=JSON.parse(raw)}catch{localStorage.removeItem(PENDING);return false}
    const {data:{user},error:ue}=await dbInit().auth.getUser();if(ue)throw ue;
    if(!user||!user.email_confirmed_at)return false;
    const {data:staff,error:se}=await db.from('staff').select('institute_id').eq('user_id',user.id).maybeSingle();if(se)throw se;
    if(staff){localStorage.removeItem(PENDING);location.href='/dashboard';return true}
    const {error}=await db.rpc('create_institute_v3',{p_name:p.name});if(error)throw error;
    localStorage.removeItem(PENDING);location.href='/dashboard';return true;
  }
  function home(){page('<div class="card"><h1>AdmissionFlow</h1><p class="muted">Admissions CRM for coaching institutes and schools.</p><div class="row"><a class="btn" href="/onboarding.html">Create your institute</a><a class="btn secondary" href="/login">Staff login</a></div></div>')}
  function verify(){
    page('<div class="card"><h1>Verify your email</h1><p>Open the verification email, then return here.</p><div class="row"><button id="verified">I verified my email</button><button id="resend" class="secondary">Resend email</button></div><p id="msg"></p><a href="/login">Back to login</a></div>');dbInit();
    document.getElementById('verified').onclick=async()=>{try{await db.auth.refreshSession();if(!(await finishPending()))msg('Email is not verified yet. Open the verification link first.','err')}catch(e){msg(e.message||String(e),'err')}};
    document.getElementById('resend').onclick=async()=>{try{const p=JSON.parse(localStorage.getItem(PENDING)||'{}');if(!p.email)throw new Error('Signup email is missing. Start signup again.');const {error}=await db.auth.resend({type:'signup',email:p.email});if(error)throw error;msg('Verification email sent again.')}catch(e){msg(e.message||String(e),'err')}};
  }
  function login(){
    page('<div class="card"><h1>Staff login</h1><form id="login" class="stack"><input name="email" type="email" autocomplete="email" placeholder="Email" required><div class="row"><input id="password" name="password" type="password" autocomplete="current-password" placeholder="Password" required><button type="button" id="showpass" class="secondary">Show</button></div><button>Login</button><p id="msg"></p></form><div class="row"><a href="/forgot-password">Forgot password?</a><a href="/onboarding.html">Create account</a></div></div>');
    const f=document.getElementById('login'),pw=document.getElementById('password');document.getElementById('showpass').onclick=()=>{pw.type=pw.type==='password'?'text':'password';document.getElementById('showpass').textContent=pw.type==='password'?'Show':'Hide'};
    f.onsubmit=async e=>{e.preventDefault();try{const x=Object.fromEntries(new FormData(f));const {data,error}=await dbInit().auth.signInWithPassword({email:x.email.trim().toLowerCase(),password:x.password});if(error)throw error;if(!data.user?.email_confirmed_at){msg('Please verify your email before logging in.','err');return}if(await finishPending())return;location.href='/dashboard'}catch(err){msg(err.message||String(err),'err')}};
  }
  function forgot(){page('<div class="card"><h1>Reset password</h1><form id="forgot" class="stack"><input name="email" type="email" autocomplete="email" placeholder="Email" required><button>Send reset email</button><p id="msg"></p></form><a href="/login">Back to login</a></div>');document.getElementById('forgot').onsubmit=async e=>{e.preventDefault();try{const email=String(new FormData(e.currentTarget).get('email')).trim().toLowerCase();const {error}=await dbInit().auth.resetPasswordForEmail(email,{redirectTo:location.origin+'/reset-password'});if(error)throw error;msg('Reset email sent. Check your inbox.')}catch(err){msg(err.message||String(err),'err')}}}
  function reset(){page('<div class="card"><h1>Choose a new password</h1><form id="reset" class="stack"><div class="row"><input name="password" id="newpw" type="password" minlength="6" autocomplete="new-password" placeholder="New password" required><button type="button" id="showpw" class="secondary">Show</button></div><input name="confirm" type="password" minlength="6" autocomplete="new-password" placeholder="Confirm password" required><button>Update password</button><p id="msg"></p></form></div>');document.getElementById('showpw').onclick=()=>{const p=document.getElementById('newpw');p.type=p.type==='password'?'text':'password';document.getElementById('showpw').textContent=p.type==='password'?'Show':'Hide'};document.getElementById('reset').onsubmit=async e=>{e.preventDefault();try{const x=Object.fromEntries(new FormData(e.currentTarget));if(x.password!==x.confirm)return msg('Passwords do not match.','err');const {error}=await dbInit().auth.updateUser({password:x.password});if(error)throw error;msg('Password updated. Redirecting…');setTimeout(()=>location.href='/login',700)}catch(err){msg(err.message||String(err),'err')}}}
  async function publicPage(slug){
    try{const {data,error}=await dbInit().rpc('public_institute_v3',{p_slug:slug});if(error)throw error;if(!data)return page('<div class="card"><h2>Institute not found</h2><a href="/">Home</a></div>');const i=data.institute,c=data.courses||[],b=data.batches||[];
      page('<div class="card"><h1>'+esc(i.name)+'</h1><p class="muted">'+esc(i.tagline||'Admissions')+'</p></div><div class="grid"><div class="card"><h2>Student enquiry</h2><form id="lead" class="stack"><input name="student_name" placeholder="Student name" required><input name="phone" placeholder="Phone" required><input name="email" type="email" placeholder="Email"><input name="class_name" placeholder="Class"><input name="board_exam" placeholder="Board / exam"><select name="course"><option value="">Course</option>'+c.map(x=>'<option>'+esc(x.name)+'</option>').join('')+'</select><select name="preferred_batch"><option value="">Preferred batch</option>'+b.map(x=>'<option>'+esc(x.name)+'</option>').join('')+'</select><button>Submit enquiry</button><p id="msg"></p></form></div><div class="card"><h2>Courses & batches</h2>'+(c.map(x=>'<div class="lead">'+esc(x.name)+'</div>').join('')||'<p class="muted">No courses yet.</p>')+b.map(x=>'<div class="lead">'+esc(x.name)+(x.timing?' — '+esc(x.timing):'')+'</div>').join('')+'</div></div>');
      document.getElementById('lead').onsubmit=async e=>{e.preventDefault();try{const x=Object.fromEntries(new FormData(e.currentTarget));const {error}=await db.rpc('submit_admission_lead_v3',{p_slug:slug,p_student_name:x.student_name,p_phone:x.phone,p_email:x.email||null,p_class_name:x.class_name||null,p_board_exam:x.board_exam||null,p_course:x.course||null,p_preferred_batch:x.preferred_batch||null,p_source:'website'});if(error)throw error;e.currentTarget.reset();msg('Enquiry submitted successfully.')}catch(err){msg(err.message||String(err),'err')}};
    }catch(e){fail(e)}}
  async function loadDashboard(){const r=await db.rpc('get_dashboard_v1');if(r.error)throw r.error;if(!r.data?.staff){page('<div class="card"><h2>No institute is linked to this account</h2><p class="muted">Your email is authenticated, but this account is not connected to an AdmissionFlow institute yet.</p><div class="row"><a class="btn" href="/onboarding.html">Create your institute</a><button id="logout" class="danger">Logout</button></div><p id="msg"></p></div>');document.getElementById('logout').onclick=async()=>{try{await db.auth.signOut();location.href='/login'}catch(e){msg(e.message||String(e),'err')}};return}state=r.data;await render('leads')}
  async function render(tab){
    try{if(!state)await loadDashboard();const i=state.institute||{},leads=state.leads||[],courses=state.courses||[],batches=state.batches||[];let body='';
      if(tab==='leads')body='<div class="card"><h2>Leads ('+leads.length+')</h2>'+(leads.map(x=>'<div class="lead"><b>'+esc(x.student_name)+'</b><div class="muted">'+esc(x.phone)+'</div><select data-lead="'+esc(x.id)+'">'+STATUSES.map(s=>'<option '+(s===(x.status||'New')?'selected':'')+'>'+s+'</option>').join('')+'</select></div>').join('')||'<p class="muted">No leads yet.</p>')+'</div>';
      else if(tab==='customize')body='<div class="card"><h2>Customize institute</h2><form id="settings" class="stack"><input name="name" value="'+esc(i.name||'')+'" minlength="2" required><input name="slug" value="'+esc(i.slug||'')+'" required><div class="notice">Public URL: /'+esc(i.slug||'')+'</div><input name="tagline" value="'+esc(i.tagline||'')+'" placeholder="Tagline"><input name="logo_url" value="'+esc(i.logo_url||'')+'" placeholder="Logo URL"><input name="primary_phone" value="'+esc(i.primary_phone||'')+'" placeholder="Phone"><input name="whatsapp_number" value="'+esc(i.whatsapp_number||'')+'" placeholder="WhatsApp"><input name="address" value="'+esc(i.address||'')+'" placeholder="Address"><input name="website_url" value="'+esc(i.website_url||'')+'" placeholder="Website"><input name="primary_color" value="'+esc(i.primary_color||'#111827')+'" placeholder="#111827"><button>Save settings</button><p id="msg"></p></form></div>';
      else if(tab==='catalog')body='<div class="grid"><div class="card"><h2>Courses</h2><form id="course" class="stack"><input name="name" placeholder="Course" required><button>Add course</button></form>'+courses.map(x=>'<div class="lead">'+esc(x.name)+'</div>').join('')+'<p id="coursemsg"></p></div><div class="card"><h2>Batches</h2><form id="batch" class="stack"><input name="name" placeholder="Batch" required><input name="timing" placeholder="Timing"><button>Add batch</button></form>'+batches.map(x=>'<div class="lead">'+esc(x.name)+(x.timing?' — '+esc(x.timing):'')+'</div>').join('')+'<p id="batchmsg"></p></div></div>';
      else body='<div class="card"><h2>Account</h2><p>'+esc(state.user?.email||'')+' — '+esc(state.staff?.role||'')+'</p><p class="muted">Public URL: /'+esc(i.slug||'')+'</p></div>';
      page('<div class="row"><h2>'+esc(i.name||'AdmissionFlow')+'</h2><button id="logout" class="danger">Logout</button></div><div class="row"><button data-tab="leads">Leads</button><button data-tab="customize">Customize</button><button data-tab="catalog">Courses & batches</button><button data-tab="staff">Account</button></div>'+body);
      document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>render(b.dataset.tab));document.getElementById('logout').onclick=async()=>{try{await db.auth.signOut();location.href='/login'}catch(e){msg(e.message||String(e),'err')}};
      document.querySelectorAll('[data-lead]').forEach(s=>s.onchange=async()=>{try{const {error}=await db.rpc('update_lead_status_v1',{p_lead:s.dataset.lead,p_status:s.value});if(error)throw error;state.leads=(state.leads||[]).map(x=>x.id===s.dataset.lead?{...x,status:s.value}:x)}catch(e){msg(e.message||String(e),'err')}});
      if(tab==='customize')document.getElementById('settings').onsubmit=async e=>{e.preventDefault();try{const x=Object.fromEntries(new FormData(e.currentTarget));const {data,error}=await db.rpc('update_institute_v4',{p_name:x.name,p_slug:x.slug,p_tagline:x.tagline,p_logo_url:x.logo_url,p_primary_phone:x.primary_phone,p_whatsapp_number:x.whatsapp_number,p_address:x.address,p_website_url:x.website_url,p_primary_color:x.primary_color});if(error)throw error;state.institute=data;await render('customize')}catch(err){msg(err.message||String(err),'err')}};
      if(tab==='catalog'){
        document.getElementById('course').onsubmit=async e=>{e.preventDefault();try{const x=Object.fromEntries(new FormData(e.currentTarget));const {data,error}=await db.rpc('create_course_v1',{p_name:x.name});if(error)throw error;state.courses=[...(state.courses||[]),data];e.currentTarget.reset();await render('catalog')}catch(err){document.getElementById('coursemsg').textContent=err.message||String(err)}};
        document.getElementById('batch').onsubmit=async e=>{e.preventDefault();try{const x=Object.fromEntries(new FormData(e.currentTarget));const {data,error}=await db.rpc('create_batch_v1',{p_name:x.name,p_timing:x.timing||''});if(error)throw error;state.batches=[...(state.batches||[]),data];e.currentTarget.reset();await render('catalog')}catch(err){document.getElementById('batchmsg').textContent=err.message||String(err)}};
      }
    }catch(e){fail(e)}
  }
  async function dashboard(){const s=await session();if(!s)return location.href='/login';if(!s.user?.email_confirmed_at)return location.href='/verify';if(await finishPending())return;await loadDashboard()}
  (async()=>{try{dbInit();const s=await session();if(routeName==='login')return login();if(routeName==='verify')return verify();if(routeName==='forgot-password')return forgot();if(routeName==='reset-password')return reset();if(routeName==='dashboard')return dashboard();if(!routeName){if(s){if(await finishPending())return;return loadDashboard()}return home()}if(routeName==='onboarding')return location.href='/onboarding.html';return publicPage(routeName)}catch(e){fail(e)}})();
})();